# Generated by Django 5.2.5 on 2025-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_alter_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
    ]
